# Generated by Django 5.2.9 on 2025-12-06 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminid', models.CharField(db_column='AdminID', max_length=10, primary_key=True, serialize=False)),
                ('fullname', models.CharField(db_column='FullName', max_length=100)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=15, null=True, unique=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=100, null=True, unique=True)),
                ('permission', models.CharField(db_column='Permission', max_length=50)),
            ],
            options={
                'db_table': 'admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staffid', models.CharField(db_column='StaffID', max_length=10, primary_key=True, serialize=False)),
                ('fullname', models.CharField(db_column='FullName', max_length=100)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=15, null=True, unique=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=8, null=True)),
            ],
            options={
                'db_table': 'staff',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerid', models.CharField(db_column='CustomerID', max_length=10, primary_key=True, serialize=False)),
                ('fullname', models.CharField(db_column='FullName', max_length=100)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=15, null=True, unique=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customerbill',
            fields=[
                ('customerbillid', models.AutoField(db_column='CustomerBillID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'customerbill',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('detailid', models.AutoField(db_column='DetailID', primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(blank=True, db_column='Quantity', null=True)),
            ],
            options={
                'db_table': 'detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoiceid', models.CharField(db_column='InvoiceID', max_length=10, primary_key=True, serialize=False)),
                ('datecreated', models.DateTimeField(blank=True, db_column='DateCreated', null=True)),
                ('tax', models.DecimalField(blank=True, db_column='Tax', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'invoice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('itemid', models.CharField(db_column='ItemID', max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=100)),
                ('price', models.DecimalField(blank=True, db_column='Price', decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=11, null=True)),
            ],
            options={
                'db_table': 'item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('managerid', models.CharField(db_column='ManagerID', max_length=10, primary_key=True, serialize=False)),
                ('fullname', models.CharField(db_column='FullName', max_length=100)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=15, null=True, unique=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=100, null=True, unique=True)),
                ('permission', models.CharField(db_column='Permission', max_length=50)),
            ],
            options={
                'db_table': 'manager',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('materialid', models.CharField(db_column='MaterialID', max_length=10, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(blank=True, db_column='Quantity', null=True)),
            ],
            options={
                'db_table': 'material',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('paymentid', models.CharField(db_column='PaymentID', max_length=10, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(blank=True, db_column='Amount', decimal_places=2, max_digits=10, null=True)),
                ('paydate', models.DateTimeField(blank=True, db_column='PayDate', null=True)),
                ('method', models.CharField(blank=True, db_column='Method', max_length=8, null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=7, null=True)),
            ],
            options={
                'db_table': 'payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('promoid', models.CharField(db_column='PromoID', max_length=10, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=255, null=True)),
                ('minvalue', models.DecimalField(blank=True, db_column='MinValue', decimal_places=2, max_digits=10, null=True)),
                ('expiredate', models.DateField(blank=True, db_column='ExpireDate', null=True)),
                ('discountpercent', models.DecimalField(blank=True, db_column='DiscountPercent', decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'promotion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rorder',
            fields=[
                ('orderid', models.CharField(db_column='OrderID', max_length=10, primary_key=True, serialize=False)),
                ('createdat', models.DateTimeField(blank=True, db_column='CreatedAt', null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=9, null=True)),
                ('quantity', models.IntegerField(blank=True, db_column='Quantity', null=True)),
            ],
            options={
                'db_table': 'rorder',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rtable',
            fields=[
                ('tableid', models.IntegerField(db_column='TableID', primary_key=True, serialize=False)),
                ('tablenumber', models.IntegerField(db_column='TableNumber')),
                ('area', models.CharField(blank=True, db_column='Area', max_length=50, null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=9, null=True)),
            ],
            options={
                'db_table': 'rtable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cashier',
            fields=[
                ('staffid', models.OneToOneField(db_column='StaffID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.staff')),
                ('education', models.CharField(blank=True, db_column='Education', max_length=50, null=True)),
            ],
            options={
                'db_table': 'cashier',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('staffid', models.OneToOneField(db_column='StaffID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.staff')),
                ('experience', models.IntegerField(blank=True, db_column='Experience', null=True)),
            ],
            options={
                'db_table': 'chef',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Supervision',
            fields=[
                ('minor_staffid', models.ForeignKey(db_column='minor_StaffID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.staff')),
            ],
            options={
                'db_table': 'supervision',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Waiter',
            fields=[
                ('staffid', models.OneToOneField(db_column='StaffID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.staff')),
                ('fluency', models.CharField(blank=True, db_column='Fluency', max_length=50, null=True)),
            ],
            options={
                'db_table': 'waiter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Qdmaterial',
            fields=[
                ('qdmaterialid', models.ForeignKey(db_column='QDMaterialID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.material')),
            ],
            options={
                'db_table': 'qdmaterial',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ypromo',
            fields=[
                ('ypromoid', models.ForeignKey(db_column='YPromoID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.promotion')),
            ],
            options={
                'db_table': 'ypromo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ptorder',
            fields=[
                ('ptorderid', models.OneToOneField(db_column='PTOrderID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.rorder')),
            ],
            options={
                'db_table': 'ptorder',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Manager', 'Manager'), ('Staff', 'Staff')], default='Staff', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
