# Generated by Django 5.2.9 on 2025-12-06 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='admin_profile',
            field=models.OneToOneField(blank=True, db_column='AdminID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.admin'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='manager_profile',
            field=models.OneToOneField(blank=True, db_column='ManagerID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.manager'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='staff_profile',
            field=models.OneToOneField(blank=True, db_column='StaffID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.staff'),
        ),
    ]
